site_name: RBACX
site_url: https://cheater121.github.io/rbacx/
repo_url: https://github.com/Cheater121/rbacx
repo_name: Cheater121/rbacx
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            merge_init_into_class: true
            show_source: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Overview: overview.md
  - Quickstart: quickstart.md
  - Adapters: adapters.md
  - Architecture: architecture.md
  - Logging: logging.md
  - API Reference: api.md
  - Security: security.md
  - Performance: performance.md
  - Metrics: metrics.md
  - Web adapters: web_adapters.md
  - Benchmarks: benchmarks.md
  - Observability stack: observability_stack.md
  - DRF example: drf_example.md
  - CI: ci.md
  - Policy authoring: policy_authoring.md
  - Reasons: reasons.md
  - Diagnostics: diagnostics.md
  - Time operators: time_operators.md
  - Migration (RBAC→ABAC): migration_rbac_to_abac.md
  - Policy catalog: policy_catalog.md
  - Policy stores: policy_stores.md
  - OpenTelemetry: otel_metrics.md
  - HTTP mapping: http_mapping.md
  - Role hierarchy: roles.md
  - Audit mode: audit_mode.md
