name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'  # cache pip wheels to speed up installs

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .
          pip install ruff mypy pytest coverage build twine pytest-asyncio

      - name: Ruff (lint)
        run: ruff check src

      - name: Mypy (types)
        run: mypy src

      - name: Pytest
        run: pytest -q

      - name: Coverage (generate XML & enforce >=80%)
        if: matrix.python-version == '3.11'
        run: |
          coverage run -m pytest -q
          coverage xml -o coverage.xml
          coverage report --fail-under=80

      - name: Upload coverage.xml
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Build (sdist & wheel) + twine check
        if: matrix.python-version == '3.11'
        run: |
          python -m build
          twine check dist/*
