name: Docs
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install MkDocs toolchain
        run: |
          python -m pip install -U pip
          pip install "mkdocs==1.6" \
                      "mkdocs-material>=9.5" \
                      "mkdocstrings[python]==0.25.1"
          pip install -e .

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build (strict)
        run: mkdocs build --strict

      - name: Deploy to gh-pages
        run: mkdocs gh-deploy --force
